### ISSUE TITLE
remove date range limitation

### ISSUE THREAD

**Issue by basings** [QuantumPhysique/trale#100]
**Is your feature request related to a problem? Please describe.**
Adding data prior to 21 is not possible. 

**Describe the solution you'd like**
No artificial limitation

**Describe alternatives you've considered**
Using openscale.

**Comment by braniii** [comment]
Hi @basings thank you for your suggestion. The input restriction only applies to manual entries. It should (hopefully!) work when importing the measured values. Initially we've added this limitations because the computational time of the interpolation scales with the overall timespan. So adding a single old measurement, e.g. 2 years in the past, the performance was really bad. With the rewrite of the computation in v0.6.0 this should be less effected.

@gwosd What do you think of simply removing this limitation?

**Comment by basings** [comment]
Thank you for your quick response. Now it makes sense why there was a limitation in the first place. I assume you switched to a rolling window now which would make the limitation obsolte.

I wasn't able to import my multi year entries from openScale, although I respected the space limited file structure as the export suggested. I tried adding the entries manually after that.

**Comment by gwosd** [comment]
@braniii Sounds like a good plan.

@basings Thank you for reporting the limitation

**Comment by braniii** [comment]
@basings I've adjusted the code so that you can add dates starting from 1970 (starting of the epoch in dart language). However, I couldn't reproduce the issue with adding backups older than 2 years. In case you are still facing issues with importing backups, please reopen this issue.
